/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.challenges;


import static org.junit.Assert.assertNotNull;

public class ArrayShiftTest {
    public void arrayShiftedProperly() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
