/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multibracketvalidation;

import org.junit.Test;
import static org.junit.Assert.*;

public class MultiBracketValidationTest {
    @Test public void testAppHasAGreeting() {

    }
}
