/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multibracketvalidation;

public class MultiBracketValidation {

    public static void main(String[] args) {

    }

    public static boolean multiBracketValidation(String input){

        return true;
    }
}
